package com.facebook.react.bridge;

public enum ReactMarkerConstants
{
  static
  {
    CREATE_REACT_CONTEXT_END = new ReactMarkerConstants("CREATE_REACT_CONTEXT_END", 1);
    PROCESS_PACKAGES_START = new ReactMarkerConstants("PROCESS_PACKAGES_START", 2);
    PROCESS_PACKAGES_END = new ReactMarkerConstants("PROCESS_PACKAGES_END", 3);
    BUILD_NATIVE_MODULE_REGISTRY_START = new ReactMarkerConstants("BUILD_NATIVE_MODULE_REGISTRY_START", 4);
    BUILD_NATIVE_MODULE_REGISTRY_END = new ReactMarkerConstants("BUILD_NATIVE_MODULE_REGISTRY_END", 5);
    BUILD_JS_MODULE_CONFIG_START = new ReactMarkerConstants("BUILD_JS_MODULE_CONFIG_START", 6);
    BUILD_JS_MODULE_CONFIG_END = new ReactMarkerConstants("BUILD_JS_MODULE_CONFIG_END", 7);
    CREATE_CATALYST_INSTANCE_START = new ReactMarkerConstants("CREATE_CATALYST_INSTANCE_START", 8);
    CREATE_CATALYST_INSTANCE_END = new ReactMarkerConstants("CREATE_CATALYST_INSTANCE_END", 9);
    RUN_JS_BUNDLE_START = new ReactMarkerConstants("RUN_JS_BUNDLE_START", 10);
    RUN_JS_BUNDLE_END = new ReactMarkerConstants("RUN_JS_BUNDLE_END", 11);
    NATIVE_MODULE_INITIALIZE_START = new ReactMarkerConstants("NATIVE_MODULE_INITIALIZE_START", 12);
    NATIVE_MODULE_INITIALIZE_END = new ReactMarkerConstants("NATIVE_MODULE_INITIALIZE_END", 13);
    SETUP_REACT_CONTEXT_START = new ReactMarkerConstants("SETUP_REACT_CONTEXT_START", 14);
    SETUP_REACT_CONTEXT_END = new ReactMarkerConstants("SETUP_REACT_CONTEXT_END", 15);
    CREATE_UI_MANAGER_MODULE_START = new ReactMarkerConstants("CREATE_UI_MANAGER_MODULE_START", 16);
    CREATE_UI_MANAGER_MODULE_END = new ReactMarkerConstants("CREATE_UI_MANAGER_MODULE_END", 17);
    CREATE_VIEW_MANAGERS_START = new ReactMarkerConstants("CREATE_VIEW_MANAGERS_START", 18);
    CREATE_VIEW_MANAGERS_END = new ReactMarkerConstants("CREATE_VIEW_MANAGERS_END", 19);
    CREATE_UI_MANAGER_MODULE_CONSTANTS_START = new ReactMarkerConstants("CREATE_UI_MANAGER_MODULE_CONSTANTS_START", 20);
    CREATE_UI_MANAGER_MODULE_CONSTANTS_END = new ReactMarkerConstants("CREATE_UI_MANAGER_MODULE_CONSTANTS_END", 21);
    NATIVE_MODULE_SETUP_START = new ReactMarkerConstants("NATIVE_MODULE_SETUP_START", 22);
    NATIVE_MODULE_SETUP_END = new ReactMarkerConstants("NATIVE_MODULE_SETUP_END", 23);
    CREATE_MODULE_START = new ReactMarkerConstants("CREATE_MODULE_START", 24);
    CREATE_MODULE_END = new ReactMarkerConstants("CREATE_MODULE_END", 25);
    PROCESS_CORE_REACT_PACKAGE_START = new ReactMarkerConstants("PROCESS_CORE_REACT_PACKAGE_START", 26);
    PROCESS_CORE_REACT_PACKAGE_END = new ReactMarkerConstants("PROCESS_CORE_REACT_PACKAGE_END", 27);
    UI_MANAGER_MODULE_CONSTANTS_CONVERT_START = new ReactMarkerConstants("UI_MANAGER_MODULE_CONSTANTS_CONVERT_START", 28);
    UI_MANAGER_MODULE_CONSTANTS_CONVERT_END = new ReactMarkerConstants("UI_MANAGER_MODULE_CONSTANTS_CONVERT_END", 29);
    CREATE_I18N_MODULE_CONSTANTS_START = new ReactMarkerConstants("CREATE_I18N_MODULE_CONSTANTS_START", 30);
    CREATE_I18N_MODULE_CONSTANTS_END = new ReactMarkerConstants("CREATE_I18N_MODULE_CONSTANTS_END", 31);
    I18N_MODULE_CONSTANTS_CONVERT_START = new ReactMarkerConstants("I18N_MODULE_CONSTANTS_CONVERT_START", 32);
    I18N_MODULE_CONSTANTS_CONVERT_END = new ReactMarkerConstants("I18N_MODULE_CONSTANTS_CONVERT_END", 33);
    CREATE_I18N_ASSETS_MODULE_START = new ReactMarkerConstants("CREATE_I18N_ASSETS_MODULE_START", 34);
    CREATE_I18N_ASSETS_MODULE_END = new ReactMarkerConstants("CREATE_I18N_ASSETS_MODULE_END", 35);
    GET_CONSTANTS_START = new ReactMarkerConstants("GET_CONSTANTS_START", 36);
    GET_CONSTANTS_END = new ReactMarkerConstants("GET_CONSTANTS_END", 37);
    INITIALIZE_MODULE_START = new ReactMarkerConstants("INITIALIZE_MODULE_START", 38);
    INITIALIZE_MODULE_END = new ReactMarkerConstants("INITIALIZE_MODULE_END", 39);
    ON_HOST_RESUME_START = new ReactMarkerConstants("ON_HOST_RESUME_START", 40);
    ON_HOST_RESUME_END = new ReactMarkerConstants("ON_HOST_RESUME_END", 41);
    ON_HOST_PAUSE_START = new ReactMarkerConstants("ON_HOST_PAUSE_START", 42);
    ON_HOST_PAUSE_END = new ReactMarkerConstants("ON_HOST_PAUSE_END", 43);
    CONVERT_CONSTANTS_START = new ReactMarkerConstants("CONVERT_CONSTANTS_START", 44);
    CONVERT_CONSTANTS_END = new ReactMarkerConstants("CONVERT_CONSTANTS_END", 45);
    PRE_REACT_CONTEXT_END = new ReactMarkerConstants("PRE_REACT_CONTEXT_END", 46);
    UNPACKER_CHECK_START = new ReactMarkerConstants("UNPACKER_CHECK_START", 47);
    UNPACKER_CHECK_END = new ReactMarkerConstants("UNPACKER_CHECK_END", 48);
    UNPACKER_BUNDLE_EXTRACTED = new ReactMarkerConstants("UNPACKER_BUNDLE_EXTRACTED", 49);
    UNPACKING_JS_BUNDLE_LOADER_CHECK_START = new ReactMarkerConstants("UNPACKING_JS_BUNDLE_LOADER_CHECK_START", 50);
    UNPACKING_JS_BUNDLE_LOADER_CHECK_END = new ReactMarkerConstants("UNPACKING_JS_BUNDLE_LOADER_CHECK_END", 51);
    UNPACKING_JS_BUNDLE_LOADER_EXTRACTED = new ReactMarkerConstants("UNPACKING_JS_BUNDLE_LOADER_EXTRACTED", 52);
    loadApplicationScript_startStringConvert = new ReactMarkerConstants("loadApplicationScript_startStringConvert", 53);
    loadApplicationScript_endStringConvert = new ReactMarkerConstants("loadApplicationScript_endStringConvert", 54);
    PRE_SETUP_REACT_CONTEXT_START = new ReactMarkerConstants("PRE_SETUP_REACT_CONTEXT_START", 55);
    PRE_SETUP_REACT_CONTEXT_END = new ReactMarkerConstants("PRE_SETUP_REACT_CONTEXT_END", 56);
    PRE_RUN_JS_BUNDLE_START = new ReactMarkerConstants("PRE_RUN_JS_BUNDLE_START", 57);
    ATTACH_MEASURED_ROOT_VIEWS_START = new ReactMarkerConstants("ATTACH_MEASURED_ROOT_VIEWS_START", 58);
    ATTACH_MEASURED_ROOT_VIEWS_END = new ReactMarkerConstants("ATTACH_MEASURED_ROOT_VIEWS_END", 59);
    CONTENT_APPEARED = new ReactMarkerConstants("CONTENT_APPEARED", 60);
    RELOAD = new ReactMarkerConstants("RELOAD", 61);
    DOWNLOAD_START = new ReactMarkerConstants("DOWNLOAD_START", 62);
    DOWNLOAD_END = new ReactMarkerConstants("DOWNLOAD_END", 63);
    REACT_CONTEXT_THREAD_START = new ReactMarkerConstants("REACT_CONTEXT_THREAD_START", 64);
    REACT_CONTEXT_THREAD_END = new ReactMarkerConstants("REACT_CONTEXT_THREAD_END", 65);
    $VALUES = new ReactMarkerConstants[] { CREATE_REACT_CONTEXT_START, CREATE_REACT_CONTEXT_END, PROCESS_PACKAGES_START, PROCESS_PACKAGES_END, BUILD_NATIVE_MODULE_REGISTRY_START, BUILD_NATIVE_MODULE_REGISTRY_END, BUILD_JS_MODULE_CONFIG_START, BUILD_JS_MODULE_CONFIG_END, CREATE_CATALYST_INSTANCE_START, CREATE_CATALYST_INSTANCE_END, RUN_JS_BUNDLE_START, RUN_JS_BUNDLE_END, NATIVE_MODULE_INITIALIZE_START, NATIVE_MODULE_INITIALIZE_END, SETUP_REACT_CONTEXT_START, SETUP_REACT_CONTEXT_END, CREATE_UI_MANAGER_MODULE_START, CREATE_UI_MANAGER_MODULE_END, CREATE_VIEW_MANAGERS_START, CREATE_VIEW_MANAGERS_END, CREATE_UI_MANAGER_MODULE_CONSTANTS_START, CREATE_UI_MANAGER_MODULE_CONSTANTS_END, NATIVE_MODULE_SETUP_START, NATIVE_MODULE_SETUP_END, CREATE_MODULE_START, CREATE_MODULE_END, PROCESS_CORE_REACT_PACKAGE_START, PROCESS_CORE_REACT_PACKAGE_END, UI_MANAGER_MODULE_CONSTANTS_CONVERT_START, UI_MANAGER_MODULE_CONSTANTS_CONVERT_END, CREATE_I18N_MODULE_CONSTANTS_START, CREATE_I18N_MODULE_CONSTANTS_END, I18N_MODULE_CONSTANTS_CONVERT_START, I18N_MODULE_CONSTANTS_CONVERT_END, CREATE_I18N_ASSETS_MODULE_START, CREATE_I18N_ASSETS_MODULE_END, GET_CONSTANTS_START, GET_CONSTANTS_END, INITIALIZE_MODULE_START, INITIALIZE_MODULE_END, ON_HOST_RESUME_START, ON_HOST_RESUME_END, ON_HOST_PAUSE_START, ON_HOST_PAUSE_END, CONVERT_CONSTANTS_START, CONVERT_CONSTANTS_END, PRE_REACT_CONTEXT_END, UNPACKER_CHECK_START, UNPACKER_CHECK_END, UNPACKER_BUNDLE_EXTRACTED, UNPACKING_JS_BUNDLE_LOADER_CHECK_START, UNPACKING_JS_BUNDLE_LOADER_CHECK_END, UNPACKING_JS_BUNDLE_LOADER_EXTRACTED, loadApplicationScript_startStringConvert, loadApplicationScript_endStringConvert, PRE_SETUP_REACT_CONTEXT_START, PRE_SETUP_REACT_CONTEXT_END, PRE_RUN_JS_BUNDLE_START, ATTACH_MEASURED_ROOT_VIEWS_START, ATTACH_MEASURED_ROOT_VIEWS_END, CONTENT_APPEARED, RELOAD, DOWNLOAD_START, DOWNLOAD_END, REACT_CONTEXT_THREAD_START, REACT_CONTEXT_THREAD_END };
  }
}

/* Location:           C:\Users\c_jealom1\Documents\Scripts\Android\Fathom_com.brynk.fathom\Fathom_com.brynk.fathom-dex2jar.jar
 * Qualified Name:     com.facebook.react.bridge.ReactMarkerConstants
 * JD-Core Version:    0.6.0
 */